name: MLflow CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      # Set up Python 3.12.7
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      # Check Env
      - name: Check Env
        run: |
          python --version
          pip --version

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0
          pip install pandas numpy scikit-learn

      - name: Set MLflow DagsHub Env
        run: |
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/viramonicaas/eksperimen_SML_ViraMonica.mlflow" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_USERNAME=viramonicaas" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV

      # Run MLflow Project (DagsHub)
      - name: Run mlflow project
        run: |
          cd MLProject
          mlflow run . --env-manager=local 2>&1 | tee mlflow.log
      
      - name: Extract RUN_ID
        run: |
          RUN_ID=$(grep -oP "run with ID '\K[0-9a-f]+'" MLProject/mlflow.log | head -n 1 || true)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Extracted RUN_ID=$RUN_ID"

      - name: Validate RUN_ID
        run: |
          if [ -z "$RUN_ID" ]; then
            echo "ERROR: RUN_ID is empty"
            echo "==== mlflow.log ===="
            cat MLProject/mlflow.log
            exit 1
          fi


      # Upload artifacts
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/

      # Log in Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Model
      - name: Build Docker Model
        run: |
          cd MLProject
          mlflow models build-docker \
          -m runs:/${RUN_ID}/model \
          -n viramonicaa/diabetes-mflow

      # Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag viramonicaa/diabetes-mflow viramonicaa/diabetes-mflow:latest

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push viramonicaa/diabetes-mflow:latest